eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
 
 microservice:
  payment-service:
    endpoints:
      endpoint:
        uri:https://PAYMENT-SERVICE/payment/doPayment

 order-service:
   endpoints:
     endpoint:
       uri:https://ORDER-SERVICE/order/bookorder
